CREATE TABLE reviews (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    car_id INTEGER REFERENCES cars(id) ON DELETE CASCADE NOT NULL,
    review TEXT NOT NULL
);